config/routes.rb
Rails.application.routes.draw do
  
  
  resources :newemails
  devise_for :newemployees
  devise_for :admins
  devise_for :employees
  resources :students
  resources :employees
  resources :admins
  resources :interviews
   resources :newemployees

 
  get 'welcome/index'
  root "welcome#index"

 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable       
         
   
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/emp.rb
class Emp < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  

  def inter
        Interview.where(employee: self.email)
    end

end

app/models/interview.rb
class Interview < ApplicationRecord
belongs_to :student
belongs_to :newemployee

end

app/models/new_admin.rb
class NewAdmin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/newemail.rb
class Newemail < ApplicationRecord
end

app/models/newemployee.rb
class Newemployee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :interviews
    		has_many :newemployees, through: :interviews
end

app/models/student.rb
class Student < ApplicationRecord
	has_many :admins
	has_many :interviews
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_action :authenticate_admin!
	
	def index
		@admin=Admin.all
		@interview=Interview.all
	end
	def new
		@interview=Interview.all
	end
	def create
	end
	def edit
	end
	

end
	

app/controllers/newemployees_controller.rb
class NewemployeesController < ApplicationController
	before_action :authenticate_newemployee!
	def new
		@interview=Interview.all
	end
	  def index
        @interview = current_employee.inter
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def index
	@student = Student.all
    end

    def new
        @student = Student.new
    end

    def create
        @student = Student.new(student_params)
        if @student.save
    redirect_to @student
  else
    render 'new'
  end

  end
    
    def show
        @student = Student.find(params[:id])
    end

    private
  def student_params
    params.require(:student).permit(:name, :phonenumber, :email, :qualification, :skills)
  end

	def edit
		@student = Student.find(params[:id])
	end
	def update
		@student = Student.find(params[:id])
		@s= @student.update_attributes(student_params)
		if @s
           redirect_to student_path(@student)
       else
           redirect_to :back
       end  
	end
  def delete
    @student = Student.find(params[:id])
    @student.destroy
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/helpers/new_admin_helper.rb
module NewAdminHelper
end

app/helpers/newemails_helper.rb
module NewemailsHelper
end

app/helpers/newemployees_helper.rb
module NewemployeesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/newemployees/new.html.erb
<% if newemployee_signed_in? %>
                      <%= current_newemployee.email %>
                      
                     <div class="float:left"> <%= link_to "Log Out",destroy_newemployee_session_path,method:"delete" %></div>
                      <%else %>
                      <%= link_to "Log In",new_newemployee_session_path%>
                      <% end%>
         

           <%- model_class = Interview -%>
<div class="container">
	 <h1> Employee Schedule</h1>
<div class="page-header">
 <!--  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1> -->
</div>

 <table class="table table-bordered">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:employee) %></th>
      <th><%= model_class.human_attribute_name(:student) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @interview.each do |interview| %>
      <tr>
        <td><%= link_to interview.id, interview_path(interview) %></td>
        <td><%= interview.date %></td>
        <td><%= interview.status %></td>
        <td><%= interview.employee %></td>
        <td><%= interview.student %></td>
        <td><%=l interview.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      interview_path(interview), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_interview_path(interview), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      interview_path(interview),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>