config/routes.rb
Rails.application.routes.draw do
  
  
  resources :newemails
  devise_for :newemployees
  devise_for :admins
  devise_for :employees
  resources :students
  resources :employees
  resources :admins
  resources :interviews
   resources :newemployees

 
  get 'welcome/index'
  root "welcome#index"

 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable       
         
   
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/emp.rb
class Emp < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  

  def inter
        Interview.where(employee: self.email)
    end

end

app/models/interview.rb
class Interview < ApplicationRecord
belongs_to :student
belongs_to :newemployee

end

app/models/new_admin.rb
class NewAdmin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/newemail.rb
class Newemail < ApplicationRecord
end

app/models/newemployee.rb
class Newemployee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :interviews
    		has_many :newemployees, through: :interviews
end

app/models/student.rb
class Student < ApplicationRecord
	has_many :admins
	has_many :interviews
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_action :authenticate_admin!
	
	def index
		@admin=Admin.all
		@interview=Interview.all
	end
	def new
		@interview=Interview.all
	end
	def create
	end
	def edit
	end
	

end
	

app/controllers/newemails_controller.rb
class NewemailsController < ApplicationController
  before_action :set_newemail, only: [:show, :edit, :update, :destroy]

  # GET /newemails
  # GET /newemails.json
  def index
    @newemails = Newemail.all
  end

  # GET /newemails/1
  # GET /newemails/1.json
  def show
  end

  # GET /newemails/new
  def new
    @newemail = Newemail.new
  end

  # GET /newemails/1/edit
  def edit
  end

  # POST /newemails
  # POST /newemails.json
  def create
    @newemail = Newemail.new(newemail_params)

    respond_to do |format|
      if @newemail.save
        format.html { redirect_to @newemail, notice: 'Newemail was successfully created.' }
        format.json { render :show, status: :created, location: @newemail }
      else
        format.html { render :new }
        format.json { render json: @newemail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newemails/1
  # PATCH/PUT /newemails/1.json
  def update
    respond_to do |format|
      if @newemail.update(newemail_params)
        format.html { redirect_to @newemail, notice: 'Newemail was successfully updated.' }
        format.json { render :show, status: :ok, location: @newemail }
      else
        format.html { render :edit }
        format.json { render json: @newemail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newemails/1
  # DELETE /newemails/1.json
  def destroy
    @newemail.destroy
    respond_to do |format|
      format.html { redirect_to newemails_url, notice: 'Newemail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newemail
      @newemail = Newemail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newemail_params
      params.require(:newemail).permit(:name, :email, :login)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def index
	@student = Student.all
    end

    def new
        @student = Student.new
    end

    def create
        @student = Student.new(student_params)
        if @student.save
    redirect_to @student
  else
    render 'new'
  end

  end
    
    def show
        @student = Student.find(params[:id])
    end

    private
  def student_params
    params.require(:student).permit(:name, :phonenumber, :email, :qualification, :skills)
  end

	def edit
		@student = Student.find(params[:id])
	end
	def update
		@student = Student.find(params[:id])
		@s= @student.update_attributes(student_params)
		if @s
           redirect_to student_path(@student)
       else
           redirect_to :back
       end  
	end
  def delete
    @student = Student.find(params[:id])
    @student.destroy
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/helpers/new_admin_helper.rb
module NewAdminHelper
end

app/helpers/newemails_helper.rb
module NewemailsHelper
end

app/helpers/newemployees_helper.rb
module NewemployeesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/newemails/_form.html.erb
<%= form_with(model: newemail, local: true) do |form| %>
  <% if newemail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(newemail.errors.count, "error") %> prohibited this newemail from being saved:</h2>

      <ul>
      <% newemail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :newemail_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :newemail_email %>
  </div>

  <div class="field">
    <%= form.label :login %>
    <%= form.text_field :login, id: :newemail_login %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/newemails/edit.html.erb
<h1>Editing Newemail</h1>

<%= render 'form', newemail: @newemail %>

<%= link_to 'Show', @newemail %> |
<%= link_to 'Back', newemails_path %>

app/views/newemails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Newemails</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Login</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @newemails.each do |newemail| %>
      <tr>
        <td><%= newemail.name %></td>
        <td><%= newemail.email %></td>
        <td><%= newemail.login %></td>
        <td><%= link_to 'Show', newemail %></td>
        <td><%= link_to 'Edit', edit_newemail_path(newemail) %></td>
        <td><%= link_to 'Destroy', newemail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Newemail', new_newemail_path %>

app/views/newemails/new.html.erb
<h1>New Newemail</h1>

<%= render 'form', newemail: @newemail %>

<%= link_to 'Back', newemails_path %>

app/views/newemails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @newemail.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @newemail.email %>
</p>

<p>
  <strong>Login:</strong>
  <%= @newemail.login %>
</p>

<%= link_to 'Edit', edit_newemail_path(@newemail) %> |
<%= link_to 'Back', newemails_path %>

app/views/students/_form.html.erb
<%= form_for @student, :html => { :class => "form-horizontal student" } do |f| %>
<div class="container col-md-6">
  <% if @student.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @student.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <%= f.label :phonenumber, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :phonenumber, :class => 'form-control' %>
    </div>
    <%=f.error_span(:phonenumber) %>
  </div>
  <div class="form-group">
    <%= f.label :qualification, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :qualification, :class => 'form-control' %>
    </div>
    <%=f.error_span(:qualification) %>
  </div>
  <div class="form-group">
    <%= f.label :skills, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :skills, :class => 'form-control' %>
    </div>
    <%=f.error_span(:skills) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                students_path, :class => 'btn btn-default' %>
    </div>
  </div>
</div>
<% end %>

app/views/students/edit.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/index.html.erb
<%- model_class = Student -%>
<div class="container">
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-bordered table-inverse">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:phonenumber) %></th>
      <th><%= model_class.human_attribute_name(:qualification) %></th>
      <th><%= model_class.human_attribute_name(:skills) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @student.each do |student| %>
      <tr>
        <td><%= link_to student.id, student_path(student) %></td>
        <td><%= student.name %></td>
        <td><%= student.email %></td>
        <td><%= student.phonenumber %></td>
        <td><%= student.qualification %></td>
        <td><%= student.skills %></td>
        <td><%=l student.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      student_path(student), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_student_path(student), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      student_path(student),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_student_path,
            :class => 'btn btn-primary' %>

app/views/students/new.html.erb
<%- model_class = Student -%>
<div class="container">
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
</div>
<%= render :partial => 'form' %>

app/views/students/show.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @student.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @student.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phonenumber) %>:</strong></dt>
  <dd><%= @student.phonenumber %></dd>
  <dt><strong><%= model_class.human_attribute_name(:qualification) %>:</strong></dt>
  <dd><%= @student.qualification %></dd>
  <dt><strong><%= model_class.human_attribute_name(:skills) %>:</strong></dt>
  <dd><%= @student.skills %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              students_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_student_path(@student), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              student_path(@student),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>